# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Configure GDM to use 100 Hz for the LG ultrawide monitor.
  services.xserver.displayManager.setupCommands = ''
    xrandr --output DP-1 --mode 100Hz
  '';

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d1e9f7ea-97fc-4dcb-94ec-0bc31c7bd1e2";
      fsType = "btrfs";
      options = [ "subvol=root" "noatime" "compress=zstd:3" ];
    };

  boot.initrd.luks.devices."nixos".device = "/dev/disk/by-uuid/9df384bc-58fd-4071-bda8-a1ca84b5b1ae";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/90C4-A446";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/d1e9f7ea-97fc-4dcb-94ec-0bc31c7bd1e2";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" "compress=zstd:3" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d1e9f7ea-97fc-4dcb-94ec-0bc31c7bd1e2";
      fsType = "btrfs";
      options = [ "subvol=home" "noatime" "compress=zstd:3" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
