#!/bin/sh

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=\@im=fcitx

xsetroot -cursor_name left_ptr
xsetroot -name xmonad
hsetroot -solid "#1d1f21"

dbus-update-activation-environment --systemd DISPLAY

xrdb -merge "$HOME/.Xresources"

xbanish -i mod4 &
dunst -config "$HOME/.config/dunst/dunstrc" &
sxhkd &
picom -b
fcitx5 -d

udiskie &
stalonetray &

xset -dpms
xset s off

exec xmonad
