name: CI

on:
  pull_request: {}
  push:
    branches: [ master ]

jobs:
  xmonad:
    name: XMonad
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3

      - uses: freckle/stack-cache-action@v2
        with:
          working-directory: xmonad

      - name: Setup Haskell & Stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: latest
          stack-no-global: true

      - name: Install XMonad C build dependencies
        run: sudo apt-get install -y
          libx11-dev libxft-dev libxinerama-dev libxrandr-dev libxss-dev

      - name: Setup GHC through Stack
        run: stack setup
        working-directory: xmonad

      - name: Build project dependencies
        run: stack build --only-dependencies
        working-directory: xmonad

      - name: Build custom XMonad config
        run: stack build
        working-directory: xmonad
