name: CI

on:
  pull_request: {}
  push:
    branches: [ master ]

jobs:
  xmonad:
    name: XMonad
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3

      - name: Setup Haskell & Stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: latest
          stack-no-global: true

      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: stack-global-${{ hashFiles('xmonad/stack.yaml') }}
          restore-keys: |
            stack-global-

      - name: Cache .stack-work
        uses: actions/cache@v3
        with:
          path: xmonad/.stack-work
          key: stack-work-${{ hashFiles('xmonad/stack.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            stack-work-

      - name: Install XMonad C build dependencies
        run: sudo apt-get install -y libx11-dev libxft-dev libxinerama-dev libxrandr-dev libxss-dev

      - name: Build custom XMonad config
        run: cd xmonad && stack build
